on:
  release:
    types: [published]
jobs:
  publish:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run get archive script
        run: sh ./scripts/get_archive.sh ${{ github.event.release.assets_url }}
