on:
  release:
    types: [published]
jobs:
  publish:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run get artifact script
        run: sh ./scripts/get_artifacts.sh ${{ github.event.release.assets_url }}
