on:
  release:
    types: [published]
jobs:
  publish:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: run get artifact script
        run: sh ./scripts/get_artifacts.sh ${{ github.event.release.assets_url }}

      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: upload artifacts to s3
        run: aws s3 sync /tmp/files/ s3://{{ secrets.AWS_BUCKET }}
