name: Trigger Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # This job only runs if it's a push to main and is a release commit
  trigger:
    name: trigger-release
    if: "contains(github.event.head_commit.message, 'release: v')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: env
        run: env
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "lacework-dev/detc"
          tag: "v0.0.5"
          fileName: "*"
          token: secrets.GH_TOKEN
          out-file-path: "files"
      - name: mkdir /tmp/files
        run: mkdir -p /tmp/files

      - name: mv files
        run: mv $GITHUB_WORKSPACE/files/* /tmp/files/
      - name: run prepare
        run: echo "trigger-release"
      - name: ls /tmp/files
        run: ls -ltR /tmp/files
